### ISSUE TITLE
not working with DMD64 D Compiler v2.070.2

### ISSUE THREAD

**Issue by lindt** [Dgame/DAT#2]
not working with DMD64 D Compiler v2.070.2.
occur should be ulong in main.d, but also some goto tricks which are not compatible.

`stdx/d/parser.d(4082): Error: goto skips declaration of variable stdx.d.parser.Parser.parsePrimaryExpression.b at stdx/d/parser.d(4110)
stdx/d/parser.d(5484): Error: goto skips declaration of variable stdx.d.parser.Parser.parseTypeSuffix.type at stdx/d/parser.d(5486)
`
